if (!('initialized' in localStorage)) {
  localStorage['initialized'] = true;

  var poems= [
    "i too am untranslatable",
    "have you dream'd contemptible dreams",
    "the clock indicates the moment",
    "magnifying and applying come I",
    "the mass of a body is a measure of its energy content",
    "peace cannot be kept by force",
    "a new idea comes suddenly",
    "all mass is interaction",
    "the truth will come out",
    "what I cannot create, i do not understand",
    "nobody understands quantum mechanics",
    "thoughts are the shadows of our feelings",
    "know your enemies and know yourself",
    "i make what it pleases me to make",
    "an invisible drawing made in the air",
    "curiosity has its own reason for existing",
    "i love to travel, but I hate to arrive",
    "wherever we are, what we hear is mostly noise",
    "we need not destroy the past. it is gone",
    "no traces left of all the busy scene",
    "the days of rejoicing are gone forever",
    "i dwelt in a city enchanted",
    "the meteor of the ocean air shall sweep the clouds no more",
    "the wind hardly flickers",
    "tall cruets of pale banana syrup to pour oozing over banana waffles",
    "our sweat becomes ice and our tears pale flakes of snow",
    "does nobody understand?",
    "the universe is infinite in all directions",
    "insanity is often the logic of an accurate mind overtasked",
    "memory is the thing you forget with",
    "memory itself is an internal rumour",
    "briefly thyself remember",
    "no creature loves an empty space",
    "surely the stars are images of love",
    "make a drawing behind your back",
    "make a stolen painting",
    "there are no shortcuts to directness",
    "america I've given you all and now I'm nothing",
    "we ourselves are the entities to be analyzed",
    "never was there a time when I did not exist",
    "the stroke of death is dealt them now",
    "bless them that curse you",
    "boards don't hit back",
    "do not try to become anything",
    "a riot is the language of the unheard",
    "don't get set into one form, adapt it and build your own",
    "breath transmuted into words",
    "pure space, timeless, yea eternal",
    "use only that which works",
    "do good to them that hate you",
    "angelheaded hipsters burning",
    "the starry dynamo in the machinery of the night",
    "i don't want my work to be an exposure of my feelings",
    "only the madman is absolutely sure",
    "freedom of any kind is the worst for creativity",
    "the world is won by those who let it go",
    "busy, busy, busy",
    "so it goes",
    "jokes can be noble",
    "time is liquid",
    "how embarrassing to be human",
    "i don't get it",
    "you were sick, but now you're well, and there's work to do",
    "history is merely a list of surprises",
    "everything was beautiful, and nothing hurt",
    "there they go, there they go",
    "science never cheered up anyone",
    "on forever's very now we stand",
    "no sunbeam ever lies",
    "nothing except the impossible shall occur",
    "the master has no possessions",
    "against boredom even gods struggle in vain"
  ]
  _(poems).each(function(text) {
    Poems.create({
      text: text
    })
  });
}
